### ISSUE TITLE
Up/Down Arrows on Min Length - can't go down

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#54] opened 2024-02-28 22:57 UTC
* Min length - can't go below the default of 4
  * I understand 4 is supposed to be the minimum, but there's no error thrown, and I can erase the 4 and move along without error

**Comment by pricemi115** [comment] 2024-03-02 15:20
Same applies to Max Length field and there is no check to ensure MaxLength >= MinLength

**Comment by hepabolu** [comment] 2024-03-02 15:22
I’m working on it, along with the fix for issue #55

**Comment by hepabolu** [comment] 2024-03-09 21:55
The code added for issue #55 simply switches min and max if minLength > maxLength. This is not yet visible in the settings form, but it is used in the configuration

**Comment by hepabolu** [comment] 2024-03-09 22:30
I cannot reproduce this now the code of issue #55 is added. @podfeet and @pricemi115 can you test this?

**Comment by pricemi115** [comment] 2024-03-09 22:36
I still see a hard floor of 4 for min/max word length and a ceiling of 12.

No error is issued if the user tried to go beyond. I am not sure an alert would be the best but maybe a beep, but that is not fair to our hearing challenged friends. See @podfeet , I am trainable).

Swapping min and max works as you describe.

**Comment by pricemi115** [comment] 2024-03-09 22:38
Also, I can delete both min and max length and I get 3 words of 4 letters each.

**Comment by pricemi115** [comment] 2024-03-09 22:39
Actually all the fields can be deleted and we seem to get the min. Example: delete num of words and I get passwords with only 2 words

**Comment by pricemi115** [comment] 2024-03-09 22:42
May need to register for the changed events for these fields and if empty reset them to the default. 

That's a trick we use in the testing software that I support at work to reset values to default.

**Comment by podfeet** [comment] 2024-03-09 22:45
good job @pricemi115! there should be some sort of "please use a number greater than 3" popup like there is if you put $ in a phone field or other type of error.

**Comment by pricemi115** [comment] 2024-03-09 22:52
For illegal values yes. An error alert is fine. But if deleted completely, just reset to default. 


And here is a nice trap. If you enter a number that is out of bounds, 
1. There is no error indication or reset to the max value
2. the generate button is disabled
3. Cannot tab off the field to another field. Users will say "website froze" or something like that.

**Comment by hepabolu** [comment] 2024-03-09 22:54
ouch. This needs more elaborate feedback.

**Comment by hepabolu** [comment] 2024-03-17 14:02
@pricemi115 and @podfeet please review

**Comment by podfeet** [comment] 2024-03-17 14:20
I don't know what "previous value" means. I haven't yet hit the generate button for the first time. Using the default value might make sense but it would be better if it did nothing at all until I fixed the error.

And why is an error showing on max length when I didn't break it? 

![CleanShot 2024-03-17 at 07 15 44@2x](https://github.com/bartificer/xkpasswd-js/assets/12651464/f989ff90-7713-4237-b4bf-7ab1d1d1d3a6)

**Comment by hepabolu** [comment] 2024-03-17 16:07
@podfeet  'previous' is the value that was there before you changed it, either the default value or the value that was correct before you changed it to an invalid one. Re max length error I should check.
Before, I had the 'generate' button disabled when there was an error. I took that out because of @pricemi115 comment about getting stuck in a loop. I can put it back.

**Comment by hepabolu** [comment] 2024-03-17 22:04
Next attempt: I updated the fields so an error message is only visible for the respective field, updated the error on top and disable the 'generate' button when there is an invalid setting.
Please review again @podfeet and @pricemi115.

**Comment by podfeet** [comment] 2024-03-19 01:42
I like how it works now - I put in 1 for min length and it showed me where the error was and the banner looked good, and the Generate button was disabled as expected.

I still managed to break it though. I was curious what pushing the up button one time would do - would it go from 1 to 2?  But it did something weirder. EVERY option got a green checkmark in it and graphically now I can't tell how many words or min and max length I have for my setting.

<img width="803" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/1ee69c17-f55e-4e98-8480-d6e46537c612">

**Comment by hepabolu** [comment] 2024-03-19 08:05
The green tick marks are standard Bootstrap behaviour. I kind of like them, because they explain that there are no more errors left and you're good to go to generate passwords.
I took the spinners out, they give more errors that help.

**Comment by podfeet** [comment] 2024-03-19 13:50
It's better but the text is still unreadable on a big screen. the check mark is obscuring the text - it says "4" for min length but you just see the corner of the character and max length is invisible. As a user I started with the min length so the very next thing I want to change is not possible for me to see. I don't think this should not have been merged into main when it's still as broken as before.

![CleanShot 2024-03-19 at 06 47 36@2x](https://github.com/bartificer/xkpasswd-js/assets/12651464/3bd2de5a-53dd-47b7-908a-419cdd2b905d)

**Comment by podfeet** [comment] 2024-03-19 14:16
I just noticed this might be a responsive design problem. See how the Dictionary English is below the label for Dictionary? The problem of obscuring the digits isn't evident if more of the elements are stacked. For example, while there are still some layout problems on mobile, this problem doesn't occur.

![CleanShot 2024-03-19 at 07 16 35@2x](https://github.com/bartificer/xkpasswd-js/assets/12651464/f3470b93-d038-44bd-8e95-48310bfdfac4)

**Comment by podfeet** [comment] 2024-03-19 14:17
and...one more comment. After a legitimate digit has been typed, the error should go away. In the current design the error is still there even though I've typed in a 5.

**Comment by hepabolu** [comment] 2024-03-19 20:58
> It's better but the text is still unreadable on a big screen. the check mark is obscuring the text - it says "4" for min length but you just see the corner of the character and max length is invisible. As a user I started with the min length so the very next thing I want to change is not possible for me to see. I don't think this should not have been merged into main when it's still as broken as before.
> 

I've removed the green tick marks as soon as the form is validated successfully. Note that this will only happen when you move out of a field, e.g. with an Enter or a Tab. That should solve the problem of invisible field content. 

The event triggers 'onChange' to avoid any flicker when there are too many events.

**Comment by hepabolu** [comment] 2024-03-19 21:05
> I just noticed this might be a responsive design problem. See how the Dictionary English is below the label for Dictionary? The problem of obscuring the digits isn't evident if more of the elements are stacked. For example, while there are still some layout problems on mobile, this problem doesn't occur.
> 

To make sure that each error message is displayed properly with it's own field I split every element into its own input-group with a col-* class to allow them to stack up full width in the small phone and next to each other in a larger screen. That explains why the input of the dictionary moves below the label; the col-* width is not wide enough.

**Comment by podfeet** [comment] 2024-03-19 21:33
You could use on keyup without flicker. It's what I use to update the totals on every digit entered on my Time Adder web app. Works great.

https://podfeet.github.io/time-adder/

**Comment by pricemi115** [comment] 2024-03-24 01:36
Sorry I have been awol recently... the only remaining issues I see is that the alphabet fields can be deleted and a default is used. If deleted, then focus is lost, should probably reset to the default?? 

Also, you can use the same character more than once. I assume this would be ok and essentially create the feature where by a repeated character would serve to increase the probability of that character being selected.

**Comment by hepabolu** [comment] 2024-03-24 16:21
@podfeet I'll see if that works better. At least it doesn't require you to go to a different field, like the onChange event requires now.

@pricemi115 deleting the alphabet and being replaced by a default, is defined as such in the Perl version: if the config set contains a set for the separator or the padding alphabet, that set is used. If the alphabet is empty and it is required, the 'symbol alphabet' (a field not in the editable settings) of the configuration is used. And if that alphabet also does not exists, the version from the DEFAULT preset is used.
That's exactly what happens here. 

Re duplicates in the alphabet: We should decide whether we should allow it or prevent it. Either way, it requires user documentation. I'm working on writing it up, but I haven't yet decided how to to make it available to the webapp user.

**Comment by podfeet** [comment] 2024-03-25 14:28
Yay! it's perfect!

**Comment by podfeet** [comment] 2024-03-25 14:42
Wait! it's perfect on desktop but on mobile the green checkmarks are still there, and the error message stays even after typing in a 4.  I have no idea how it's possible for the behaviors to be different, unless somehow I'm testing two different versions at the same time? I'm not even sure I know how to do that.

<img width="366" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/fc0e6d0a-63bd-4e6a-b37d-335521c092b0">

**Comment by hepabolu** [comment] 2024-04-07 16:07
@podfeet did you find your issue on the simulator or on your phone?

**Comment by hepabolu** [comment] 2024-05-04 11:41
I've tried to reproduce this on my real iPhone 15 Pro Max (and beta.xkpasswd.net) and I can see the red error message. The popup that flashes by is created by the browser based on the attributes in the input element. It also flashes on my phone, until I move the focus to a different field in which case the popup stays up.

I have no idea how I can influence the behavior of that popup.

**Comment by hepabolu** [comment] 2024-06-22 13:26
For now I will close this issue, if there are more issues surrounding this behaviour, let's make a new issue.

**Closed by hepabolu** 2024-06-22 13:26 UTC
Labels: Waiting for review
