### ISSUE TITLE
Changing settings doesn't change the passwords created (on live beta)

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#46] opened 2024-02-20 04:33 UTC
Expected Behavior:

Changing things in settings should generate passwords with those changes.

Experienced behavior:

Changes in Settings are not reflected in generated passwords.

I tried saving first, but Saving rerenders the page with settings folded up and changes erased.

**Comment by pricemi115** [comment] 2024-02-24 21:48
dibs
Also reproduced when running locally using commit#2abd176b1679df894f3173881bf5c7920a69acd1

**Comment by hepabolu** [comment] 2024-02-24 21:54
Sorry, I’m already working on this. It’s in fact a duplicate of issue #13. I will close this issue as a duplicate. Sorry haven’t done before.

**Closed** 2024-02-24 21:55 UTC
Labels: duplicate
